export const UPDATE_TEMP_LOGIN_USERNAME = 'UPDATE_TEMP_LOGIN_USERNAME';
export const UPDATE_TEMP_LOGIN_PASSWORD = 'UPDATE_TEMP_LOGIN_PASSWORD';
export const UPDATE_TEMP_SIGNUP_NAME = 'UPDATE_TEMP_SIGNUP_NAME';
export const UPDATE_TEMP_SIGNUP_USERNAME = 'UPDATE_TEMP_SIGNUP_USERNAME';
export const UPDATE_TEMP_SIGNUP_PASSWORD = 'UPDATE_TEMP_SIGNUP_PASSWORD';
export const UPDATE_TEMP_SIGNUP_PASSWORD_RETYPE = 'UPDATE_TEMP_SIGNUP_PASSWORD_RETYPE';
export const UPDATE_TEMP_SIGNUP_EMAIL = 'UPDATE_TEMP_SIGNUP_EMAIL';
export const UPDATE_TEMP_SIGNUP_PHONE_NUMBER = 'UPDATE_TEMP_SIGNUP_PHONE_NUMBER';
export const UPDATE_TEMP_SIGNUP_TFA_CODE = 'UPDATE_TEMP_SIGNUP_TFA_CODE';

export const LOG_IN = 'LOG_IN';
export const LOG_IN_SUCCESS = 'LOGIN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const CONFIRM_LOGIN = 'CONFIRM_LOGIN';
export const CONFIRM_LOGIN_SUCCESS = 'CONFIRM_LOGIN_SUCCESS';
export const CONFIRM_LOGIN_FAILURE = 'CONFIRM_LOGIN_FAILURE';

export const LOG_OUT = 'LOG_OUT';
export const LOG_OUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOG_OUT_FAILURE = 'LOG_OUT_FAILURE';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const CONFIRM_SIGNUP = 'CONFIRM_SIGNUP';
export const CONFIRM_SIGNUP_SUCCESS = 'CONFIRM_SIGNUP_SUCCESS';
export const CONFIRM_SIGNUP_FAILURE = 'CONFIRM_SIGNUP_FAILURE';

export const RESEND_SIGNUP = 'RESEND_SIGNUP';
export const RESEND_SIGNUP_SUCCESS = 'RESEND_SIGNUP_SUCCESS';
export const RESEND_SIGNUP_FAILURE = 'RESEND_SIGNUP_FAILURE';

export const SHOW_LOGIN_CONFIRMATION_MODAL = 'SHOW_LOGIN_CONFIRMATION_MODAL';
export const SHOW_SIGNUP_CONFIRMATION_MODAL = 'SHOW_SIGNUP_CONFIRMATION_MODAL';
export const SHOW_LOGIN_SCREEN = 'SHOW_LOGIN_SCREEN';
export const SHOW_LOGGED_IN_SCREEN = 'SHOW_LOGGED_IN_SCREEN';
