export const NAV_LOGIN_CONFIRMATION_MODAL = 'SHOW_LOGIN_CONFIRMATION_MODAL';
export const NAV_SIGNUP_CONFIRMATION_MODAL = 'SHOW_SIGNUP_CONFIRMATION_MODAL';
export const NAV_LOGIN_SCREEN = 'SHOW_LOGIN_SCREEN';
export const NAV_LOGGED_IN_SCREEN = 'SHOW_LOGGED_IN_SCREEN';
